CREATE SCHEMA energystorage;
CREATE SCHEMA enviroassoc;
CREATE SCHEMA enviroequip;
CREATE SCHEMA generator;
CREATE SCHEMA multifuel;
CREATE SCHEMA owner;
CREATE SCHEMA plant;
CREATE SCHEMA solar;
CREATE SCHEMA utility;
CREATE SCHEMA wind;


CREATE TABLE energystorage.operable(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	operating_month BIGINT,
	operating_year BIGINT,
	nameplate_energy_capacity_mwh VARCHAR,
	maximum_charge_rate_mw VARCHAR,
	maximum_discharge_rate_mw VARCHAR,
	storage_technology_1 VARCHAR,
	storage_technology_2 VARCHAR,
	storage_technology_3 VARCHAR,
	storage_technology_4 VARCHAR,
	nameplate_reactive_power_rating VARCHAR,
	storage_enclosure_type VARCHAR,
	arbitrage VARCHAR,
	frequency_regulation VARCHAR,
	load_following VARCHAR,
	ramping_spinning_reserve VARCHAR,
	colocated_renewable_firming VARCHAR,
	transmission_and_distribution_deferral VARCHAR,
	system_peak_shaving VARCHAR,
	load_management VARCHAR,
	voltage_or_reactive_power_support VARCHAR,
	backup_power VARCHAR,
	excess_wind_and_solar_generation VARCHAR,
	ac_coupled VARCHAR,
	dc_coupled VARCHAR,
	dc_tightly_coupled VARCHAR,
	independent VARCHAR,
	direct_support_of_another_unit VARCHAR,
	direct_support_plant_id_1 VARCHAR,
	direct_support_gen_id_1 VARCHAR,
	direct_support_plant_id_2 VARCHAR,
	direct_support_gen_id_2 VARCHAR,
	direct_support_plant_id_3 VARCHAR,
	direct_support_gen_id_3 VARCHAR,
	support_td_asset VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE energystorage.proposed(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	current_month BIGINT,
	current_year BIGINT,
	nameplate_energy_capacity_mwh VARCHAR,
	maximum_charge_rate_mw VARCHAR,
	maximum_discharge_rate_mw VARCHAR,
	storage_technology_1 VARCHAR,
	storage_technology_2 VARCHAR,
	storage_technology_3 VARCHAR,
	storage_technology_4 VARCHAR,
	nameplate_reactive_power_rating VARCHAR,
	storage_enclosure_type VARCHAR,
	arbitrage VARCHAR,
	frequency_regulation VARCHAR,
	load_following VARCHAR,
	ramping_spinning_reserve VARCHAR,
	colocated_renewable_firming VARCHAR,
	transmission_and_distribution_deferral VARCHAR,
	system_peak_shaving VARCHAR,
	load_management VARCHAR,
	voltage_or_reactive_power_support VARCHAR,
	backup_power VARCHAR,
	excess_wind_and_solar_generation VARCHAR,
	ac_coupled VARCHAR,
	dc_coupled VARCHAR,
	dc_tightly_coupled BOOLEAN,
	independent VARCHAR,
	direct_support_of_another_unit VARCHAR,
	direct_support_plant_id_1 VARCHAR,
	direct_support_gen_id_1 VARCHAR,
	direct_support_plant_id_2 VARCHAR,
	direct_support_gen_id_2 VARCHAR,
	direct_support_plant_id_3 VARCHAR,
	direct_support_gen_id_3 VARCHAR,
	support_td_asset VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE energystorage.retired_and_canceled(
	utility_id VARCHAR,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector VARCHAR,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw VARCHAR,
	winter_capacity_mw VARCHAR,
	operating_month VARCHAR,
	operating_year VARCHAR,
	retirement_month VARCHAR,
	retirement_year VARCHAR,
	nameplate_energy_capacity_mwh VARCHAR,
	maximum_charge_rate_mw VARCHAR,
	maximum_discharge_rate_mw VARCHAR,
	storage_technology_1 VARCHAR,
	storage_technology_2 VARCHAR,
	storage_technology_3 VARCHAR,
	storage_technology_4 VARCHAR,
	nameplate_reactive_power_rating VARCHAR,
	storage_enclosure_type VARCHAR,
	arbitrage VARCHAR,
	frequency_regulation VARCHAR,
	load_following VARCHAR,
	ramping_spinning_reserve VARCHAR,
	colocated_renewable_firming VARCHAR,
	transmission_and_distribution_deferral VARCHAR,
	system_peak_shaving VARCHAR,
	load_management VARCHAR,
	voltage_or_reactive_power_support VARCHAR,
	backup_power VARCHAR,
	excess_wind_and_solar_generation VARCHAR,
	ac_coupled VARCHAR,
	dc_coupled VARCHAR,
	dc_tightly_coupled VARCHAR,
	independent VARCHAR,
	direct_support_of_another_unit VARCHAR,
	direct_support_plant_id_1 VARCHAR,
	direct_support_gen_id_1 VARCHAR,
	direct_support_plant_id_2 VARCHAR,
	direct_support_gen_id_2 VARCHAR,
	direct_support_plant_id_3 VARCHAR,
	direct_support_gen_id_3 VARCHAR,
	support_td_asset VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_cooling(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	cooling_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_generator(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	generator_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_mercury(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	mercury_control_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_nox(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	nox_control_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_particulate_matter(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	particulate_matter_control_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_so2(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	so2_control_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.boiler_stack_flue(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	boiler_id VARCHAR,
	stack_flue_id VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroassoc.emissions_control_equipment(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	equipment_type VARCHAR,
	particulate_matter_control_id VARCHAR,
	so2_control_id VARCHAR,
	nox_control_id VARCHAR,
	mercury_control_id VARCHAR,
	acid_gas_control BOOLEAN,
	status VARCHAR,
	inservice_month VARCHAR,
	inservice_year VARCHAR,
	retirement_month VARCHAR,
	retirement_year VARCHAR,
	total_cost_thousand_dollars VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroequip.boiler_info_design_parameters(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	boiler_id VARCHAR,
	hrsg VARCHAR,
	boiler_status VARCHAR,
	type_of_boiler VARCHAR,
	inservice_month VARCHAR,
	inservice_year VARCHAR,
	retirement_month VARCHAR,
	retirement_year VARCHAR,
	firing_type_1 VARCHAR,
	firing_type_2 VARCHAR,
	firing_type_3 VARCHAR,
	max_steam_flow_thousand_pounds_per_hour VARCHAR,
	firing_rate_using_coal_01_tons_per_hour VARCHAR,
	firing_rate_using_petroleum_01_barrels_per_hour VARCHAR,
	firing_rate_using_gas_01_mcf_per_hour VARCHAR,
	firing_rate_using_other_fuels VARCHAR,
	waste_heat_input_million_btu_per_hour VARCHAR,
	primary_fuel_1 VARCHAR,
	primary_fuel_2 VARCHAR,
	primary_fuel_3 VARCHAR,
	primary_fuel_4 VARCHAR,
	turndown_ratio VARCHAR,
	efficiency_100_load VARCHAR,
	efficiency_50_load VARCHAR,
	air_flow_100_load_cubic_feet_per_minute VARCHAR,
	wet_dry_bottom VARCHAR,
	fly_ash_reinjection VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroequip.cooling(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	cooling_id VARCHAR,
	cooling_status VARCHAR,
	inservice_month BIGINT,
	inservice_year BIGINT,
	cooling_type_1 VARCHAR,
	cooling_type_2 VARCHAR,
	cooling_type_3 BOOLEAN,
	cooling_type_4 VARCHAR,
	percent_dry_cooling VARCHAR,
	cooling_water_source VARCHAR,
	cooling_water_discharge VARCHAR,
	water_source_code VARCHAR,
	water_type_code VARCHAR,
	intake_rate_at_100_gallons_per_minute VARCHAR,
	chlorine_inservice_month VARCHAR,
	chlorine_inservice_year VARCHAR,
	pond_inservice_month VARCHAR,
	pond_inservice_year VARCHAR,
	pond_surface_area_acres VARCHAR,
	pond_volume_acre_feet VARCHAR,
	tower_inservice_month VARCHAR,
	tower_inservice_year VARCHAR,
	tower_type_1 VARCHAR,
	tower_type_2 VARCHAR,
	tower_type_3 VARCHAR,
	tower_type_4 VARCHAR,
	tower_water_rate_gallons_per_minute VARCHAR,
	power_requirement_mw VARCHAR,
	cost_total_thousand_dollars VARCHAR,
	cost_ponds_thousand_dollars VARCHAR,
	cost_towers_thousand_dollars VARCHAR,
	cost_chlorine_equipment_thousand_dollars VARCHAR,
	intake_distance_shore_feet VARCHAR,
	outlet_distance_shore_feet VARCHAR,
	intake_distance_surface_feet VARCHAR,
	outlet_distance_surface_feet VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroequip.emission_standards_strategies(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	boiler_id VARCHAR,
	boiler_status VARCHAR,
	type_of_boiler VARCHAR,
	new_source_review VARCHAR,
	new_source_review_permit VARCHAR,
	new_source_review_month VARCHAR,
	new_source_review_year VARCHAR,
	regulation_sulfur VARCHAR,
	standard_sulfur_rate VARCHAR,
	standard_sulfur_percent_scrubbed VARCHAR,
	unit_sulfur VARCHAR,
	period_sulfur VARCHAR,
	compliance_year_sulfur VARCHAR,
	sulfur_dioxide_control_existing_strategy_1 VARCHAR,
	sulfur_dioxide_control_existing_strategy_2 VARCHAR,
	sulfur_dioxide_control_existing_strategy_3 VARCHAR,
	sulfur_dioxide_control_proposed_strategy_1 VARCHAR,
	sulfur_dioxide_control_proposed_strategy_2 VARCHAR,
	sulfur_dioxide_control_proposed_strategy_3 VARCHAR,
	regulation_nitrogen VARCHAR,
	standard_nitrogen_rate VARCHAR,
	unit_nitrogen VARCHAR,
	period_nitrogen VARCHAR,
	compliance_year_nitrogen VARCHAR,
	nitrogen_oxide_control_existing_strategy_1 VARCHAR,
	nitrogen_oxide_control_existing_strategy_2 VARCHAR,
	nitrogen_oxide_control_existing_strategy_3 VARCHAR,
	nitrogen_oxide_control_proposed_strategy_1 VARCHAR,
	nitrogen_oxide_control_proposed_strategy_2 VARCHAR,
	nitrogen_oxide_control_proposed_strategy_3 VARCHAR,
	regulation_particulate VARCHAR,
	standard_particulate_rate VARCHAR,
	unit_particulate VARCHAR,
	period_particulate VARCHAR,
	compliance_year_particulate VARCHAR,
	regulation_mercury VARCHAR,
	compliance_year_mercury VARCHAR,
	mercury_control_existing_strategy_1 VARCHAR,
	mercury_control_existing_strategy_2 VARCHAR,
	mercury_control_existing_strategy_3 VARCHAR,
	mercury_control_proposed_strategy_1 VARCHAR,
	mercury_control_proposed_strategy_2 VARCHAR,
	mercury_control_proposed_strategy_3 VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroequip.fgd(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	so2_control_id VARCHAR,
	so2_type_1 VARCHAR,
	so2_type_2 VARCHAR,
	so2_type_3 VARCHAR,
	so2_type_4 VARCHAR,
	sorbent_type_1 VARCHAR,
	sorbent_type_2 VARCHAR,
	sorbent_type_3 VARCHAR,
	sorbent_type_4 BOOLEAN,
	byproduct_recovery VARCHAR,
	pond_landfill_requirements_acre_foot_per_year NUMERIC(18, 6),
	sludge_pond VARCHAR,
	sludge_pond_lined VARCHAR,
	flue_gas_bypass_fgd VARCHAR,
	specifications_of_coal_ash VARCHAR,
	specifications_of_coal_sulfur VARCHAR,
	fgd_trains_total VARCHAR,
	fgd_trains_100 VARCHAR,
	removal_efficiency_of_sulfur VARCHAR,
	sulfur_emission_rate_pounds_per_hour VARCHAR,
	flue_gas_exit_rate_cubic_feet_per_minute VARCHAR,
	flue_gas_exit_temperature_fahrenheit VARCHAR,
	flue_gas_entering_fgd_percent_of_total VARCHAR,
	cost_structure_thousand_dollars VARCHAR,
	cost_disposal_thousand_dollars VARCHAR,
	cost_other_thousand_dollars VARCHAR,
	cost_total_thousand_dollars VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroequip.fgp(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	particulate_matter_control_id VARCHAR,
	collector_type_1 VARCHAR,
	collector_type_2 VARCHAR,
	collector_type_3 VARCHAR,
	fuel_specification_ash_coal VARCHAR,
	fuel_specification_ash_petroleum VARCHAR,
	fuel_specification_sulfur_coal VARCHAR,
	fuel_specification_sulfur_petroleum VARCHAR,
	collection_efficiency VARCHAR,
	emission_rate_pounds_per_hour VARCHAR,
	gas_exit_rate_cubic_feet_per_minute VARCHAR,
	gas_exit_temperature_fahrenheit VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE enviroequip.stack_flue(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	stack_or_flue_id VARCHAR,
	inservice_month VARCHAR,
	inservice_year VARCHAR,
	stack_flue_status VARCHAR,
	stack_height_feet VARCHAR,
	area_at_top_square_feet VARCHAR,
	exit_rate_100_cubic_feet_per_minute VARCHAR,
	exit_rate_50_cubic_feet_per_minute VARCHAR,
	exit_temperature_100_fahrenheit VARCHAR,
	exit_temperature_50_fahrenheit VARCHAR,
	exit_velocity_100_feet_per_second VARCHAR,
	exit_velocity_50_feet_per_second VARCHAR,
	exit_temperature_summer_fahrenheit VARCHAR,
	exit_temperature_winter_fahrenheit VARCHAR,
	exit_temperature_measured_or_estimated VARCHAR,
	steam_plant_type BIGINT,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE generator.operable(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	unit_code VARCHAR,
	ownership VARCHAR,
	duct_burners VARCHAR,
	can_bypass_heat_recovery_steam_generator VARCHAR,
	rtoiso_lmp_node_designation VARCHAR,
	rtoiso_location_designation_for_reporting_wholesale_sales_data_ VARCHAR,
	nameplate_capacity_mw NUMERIC(18, 6),
	nameplate_power_factor NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	minimum_load_mw VARCHAR,
	uprate_or_derate_completed_during_year VARCHAR,
	month_uprate_or_derate_completed VARCHAR,
	year_uprate_or_derate_completed VARCHAR,
	status VARCHAR,
	synchronized_to_transmission_grid VARCHAR,
	operating_month BIGINT,
	operating_year BIGINT,
	planned_retirement_month VARCHAR,
	planned_retirement_year VARCHAR,
	associated_with_combined_heat_and_power_system VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	topping_or_bottoming VARCHAR,
	energy_source_1 VARCHAR,
	energy_source_2 VARCHAR,
	energy_source_3 VARCHAR,
	energy_source_4 VARCHAR,
	energy_source_5 VARCHAR,
	energy_source_6 VARCHAR,
	startup_source_1 VARCHAR,
	startup_source_2 VARCHAR,
	startup_source_3 VARCHAR,
	startup_source_4 VARCHAR,
	solid_fuel_gasification_system VARCHAR,
	carbon_capture_technology VARCHAR,
	turbines_or_hydrokinetic_buoys VARCHAR,
	time_from_cold_shutdown_to_full_load VARCHAR,
	fluidized_bed_technology VARCHAR,
	pulverized_coal_technology VARCHAR,
	stoker_technology VARCHAR,
	other_combustion_technology VARCHAR,
	subcritical_technology VARCHAR,
	supercritical_technology VARCHAR,
	ultrasupercritical_technology VARCHAR,
	planned_net_summer_capacity_uprate_mw VARCHAR,
	planned_net_winter_capacity_uprate_mw VARCHAR,
	planned_uprate_month VARCHAR,
	planned_uprate_year VARCHAR,
	planned_net_summer_capacity_derate_mw VARCHAR,
	planned_net_winter_capacity_derate_mw VARCHAR,
	planned_derate_month VARCHAR,
	planned_derate_year VARCHAR,
	planned_new_prime_mover VARCHAR,
	planned_energy_source_1 VARCHAR,
	planned_new_nameplate_capacity_mw VARCHAR,
	planned_repower_month VARCHAR,
	planned_repower_year VARCHAR,
	other_planned_modifications VARCHAR,
	other_modifications_month VARCHAR,
	other_modifications_year VARCHAR,
	multiple_fuels VARCHAR,
	cofire_fuels VARCHAR,
	switch_between_oil_and_natural_gas VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE generator.proposed(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	unit_code VARCHAR,
	ownership VARCHAR,
	duct_burners VARCHAR,
	can_bypass_heat_recovery_steam_generator VARCHAR,
	rtoiso_lmp_node_designation VARCHAR,
	rtoiso_location_designation_for_reporting_wholesale_sales_data_ VARCHAR,
	nameplate_capacity_mw NUMERIC(18, 6),
	nameplate_power_factor VARCHAR,
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw VARCHAR,
	status VARCHAR,
	effective_month BIGINT,
	effective_year BIGINT,
	current_month BIGINT,
	current_year BIGINT,
	associated_with_combined_heat_and_power_system VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	previously_canceled VARCHAR,
	energy_source_1 VARCHAR,
	energy_source_2 VARCHAR,
	energy_source_3 VARCHAR,
	energy_source_4 VARCHAR,
	energy_source_5 VARCHAR,
	energy_source_6 VARCHAR,
	turbines_or_hydrokinetic_buoys VARCHAR,
	fluidized_bed_technology VARCHAR,
	pulverized_coal_technology VARCHAR,
	stoker_technology BOOLEAN,
	other_combustion_technology VARCHAR,
	subcritical_technology VARCHAR,
	supercritical_technology VARCHAR,
	ultrasupercritical_technology VARCHAR,
	solid_fuel_gasification_system VARCHAR,
	carbon_capture_technology VARCHAR,
	multiple_fuels VARCHAR,
	switch_between_oil_and_natural_gas VARCHAR,
	cofire_fuels VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE generator.retired_and_canceled(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	unit_code VARCHAR,
	ownership VARCHAR,
	duct_burners VARCHAR,
	can_bypass_heat_recovery_steam_generator VARCHAR,
	rtoiso_lmp_node_designation VARCHAR,
	rtoiso_location_designation_for_reporting_wholesale_sales_data_ VARCHAR,
	nameplate_capacity_mw NUMERIC(18, 6),
	nameplate_power_factor VARCHAR,
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	minimum_load_mw VARCHAR,
	uprate_or_derate_completed_during_year VARCHAR,
	month_uprate_or_derate_completed VARCHAR,
	year_uprate_or_derate_completed VARCHAR,
	status VARCHAR,
	synchronized_to_transmission_grid VARCHAR,
	operating_month VARCHAR,
	operating_year VARCHAR,
	retirement_month VARCHAR,
	retirement_year VARCHAR,
	associated_with_combined_heat_and_power_system VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	topping_or_bottoming VARCHAR,
	energy_source_1 VARCHAR,
	energy_source_2 VARCHAR,
	energy_source_3 VARCHAR,
	energy_source_4 VARCHAR,
	energy_source_5 VARCHAR,
	energy_source_6 VARCHAR,
	startup_source_1 VARCHAR,
	startup_source_2 VARCHAR,
	startup_source_3 VARCHAR,
	startup_source_4 VARCHAR,
	solid_fuel_gasification_system VARCHAR,
	carbon_capture_technology VARCHAR,
	turbines_or_hydrokinetic_buoys VARCHAR,
	time_from_cold_shutdown_to_full_load VARCHAR,
	fluidized_bed_technology VARCHAR,
	pulverized_coal_technology VARCHAR,
	stoker_technology VARCHAR,
	other_combustion_technology VARCHAR,
	subcritical_technology VARCHAR,
	supercritical_technology VARCHAR,
	ultrasupercritical_technology BOOLEAN,
	multiple_fuels VARCHAR,
	cofire_fuels VARCHAR,
	switch_between_oil_and_natural_gas VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE multifuel.operable(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	operating_month BIGINT,
	operating_year BIGINT,
	energy_source_1 VARCHAR,
	energy_source_2 VARCHAR,
	multiple_fuels VARCHAR,
	cofire_fuels VARCHAR,
	cofire_energy_source_1 VARCHAR,
	cofire_energy_source_2 VARCHAR,
	cofire_energy_source_3 VARCHAR,
	cofire_energy_source_4 VARCHAR,
	cofire_energy_source_5 VARCHAR,
	cofire_energy_source_6 VARCHAR,
	switch_between_oil_and_natural_gas VARCHAR,
	switch_when_operating VARCHAR,
	net_summer_capacity_with_natural_gas_mw VARCHAR,
	net_winter_capacity_with_natural_gas_mw VARCHAR,
	net_summer_capacity_with_oil_mw VARCHAR,
	net_winter_capacity_with_oil_mw VARCHAR,
	time_to_switch_from_gas_to_oil VARCHAR,
	time_to_switch_from_oil_to_gas VARCHAR,
	factors_that_limit_switching VARCHAR,
	storage_limits BOOLEAN,
	air_permit_limits BOOLEAN,
	other_limits BOOLEAN,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE multifuel.proposed(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw VARCHAR,
	current_month BIGINT,
	current_year BIGINT,
	energy_source_1 VARCHAR,
	energy_source_2 VARCHAR,
	multiple_fuels VARCHAR,
	cofire_fuels VARCHAR,
	cofire_energy_source_1 VARCHAR,
	cofire_energy_source_2 VARCHAR,
	cofire_energy_source_3 VARCHAR,
	cofire_energy_source_4 VARCHAR,
	cofire_energy_source_5 VARCHAR,
	cofire_energy_source_6 VARCHAR,
	switch_between_oil_and_natural_gas VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE multifuel.retired_and_canceled(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw VARCHAR,
	winter_capacity_mw VARCHAR,
	operating_month BIGINT,
	operating_year BIGINT,
	retirement_month BIGINT,
	retirement_year BIGINT,
	energy_source_1 VARCHAR,
	energy_source_2 VARCHAR,
	multiple_fuels VARCHAR,
	cofire_fuels VARCHAR,
	cofire_energy_source_1 VARCHAR,
	cofire_energy_source_2 VARCHAR,
	cofire_energy_source_3 VARCHAR,
	cofire_energy_source_4 VARCHAR,
	cofire_energy_source_5 VARCHAR,
	cofire_energy_source_6 VARCHAR,
	switch_between_oil_and_natural_gas VARCHAR,
	switch_when_operating VARCHAR,
	net_summer_capacity_with_natural_gas_mw VARCHAR,
	net_winter_capacity_with_natural_gas_mw VARCHAR,
	net_summer_capacity_with_oil_mw VARCHAR,
	net_winter_capacity_with_oil_mw VARCHAR,
	time_to_switch_from_gas_to_oil VARCHAR,
	time_to_switch_from_oil_to_gas VARCHAR,
	factors_that_limit_switching VARCHAR,
	storage_limits BOOLEAN,
	air_permit_limits BOOLEAN,
	other_limits BOOLEAN,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE owner.ownership(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	owner_name VARCHAR,
	owner_street_address VARCHAR,
	owner_city VARCHAR,
	owner_state VARCHAR,
	owner_zip BIGINT,
	ownership_id BIGINT,
	percent_owned NUMERIC(18, 6),
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE plant.plant(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	street_address VARCHAR,
	city VARCHAR,
	state VARCHAR,
	zip BIGINT,
	county VARCHAR,
	latitude NUMERIC(18, 6),
	longitude NUMERIC(18, 6),
	nerc_region VARCHAR,
	balancing_authority_code VARCHAR,
	balancing_authority_name VARCHAR,
	name_of_water_source VARCHAR,
	primary_purpose_naics_code BIGINT,
	regulatory_status BOOLEAN,
	sector BIGINT,
	sector_name VARCHAR,
	ferc_cogeneration_status VARCHAR,
	ferc_cogeneration_docket_number VARCHAR,
	ferc_small_power_producer_status VARCHAR,
	ferc_small_power_producer_docket_number VARCHAR,
	ferc_exempt_wholesale_generator_status VARCHAR,
	ferc_exempt_wholesale_generator_docket_number VARCHAR,
	ash_impoundment VARCHAR,
	ash_impoundment_lined VARCHAR,
	ash_impoundment_status VARCHAR,
	transmission_or_distribution_system_owner VARCHAR,
	transmission_or_distribution_system_owner_id VARCHAR,
	transmission_or_distribution_system_owner_state VARCHAR,
	grid_voltage_kv VARCHAR,
	grid_voltage_2_kv VARCHAR,
	grid_voltage_3_kv VARCHAR,
	energy_storage VARCHAR,
	natural_gas_ldc_name VARCHAR,
	natural_gas_pipeline_name_1 VARCHAR,
	natural_gas_pipeline_name_2 VARCHAR,
	natural_gas_pipeline_name_3 VARCHAR,
	pipeline_notes VARCHAR,
	natural_gas_storage VARCHAR,
	liquefied_natural_gas_storage VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE solar.operable(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	operating_month BIGINT,
	operating_year BIGINT,
	lenses_mirrors VARCHAR,
	singleaxis_tracking VARCHAR,
	dualaxis_tracking VARCHAR,
	fixed_tilt VARCHAR,
	bifacial VARCHAR,
	east_west_fixed_tilt VARCHAR,
	parabolic_trough VARCHAR,
	linear_fresnel BOOLEAN,
	power_tower VARCHAR,
	dish_engine BOOLEAN,
	other_solar_technology VARCHAR,
	azimuth_angle VARCHAR,
	tilt_angle VARCHAR,
	dc_net_capacity_mw VARCHAR,
	crystalline_silicon VARCHAR,
	thinfilm_cdte VARCHAR,
	thinfilm_asi VARCHAR,
	thinfilm_cigs VARCHAR,
	thinfilm_other VARCHAR,
	other_materials VARCHAR,
	net_metering_agreement VARCHAR,
	net_metering_dc_capacity_mw VARCHAR,
	virtual_net_metering_agreement VARCHAR,
	virtual_net_metering_dc_capacity_mw VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE solar.retired_and_canceled(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology BOOLEAN,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw VARCHAR,
	operating_month VARCHAR,
	operating_year VARCHAR,
	retirement_month VARCHAR,
	retirement_year VARCHAR,
	lenses_mirrors BOOLEAN,
	singleaxis_tracking VARCHAR,
	dualaxis_tracking VARCHAR,
	fixed_tilt VARCHAR,
	bifacial VARCHAR,
	east_west_fixed_tilt VARCHAR,
	parabolic_trough VARCHAR,
	linear_fresnel BOOLEAN,
	power_tower VARCHAR,
	dish_engine VARCHAR,
	other_solar_technology VARCHAR,
	azimuth_angle VARCHAR,
	tilt_angle VARCHAR,
	dc_net_capacity_mw VARCHAR,
	crystalline_silicon VARCHAR,
	thinfilm_cdte BOOLEAN,
	thinfilm_asi VARCHAR,
	thinfilm_cigs VARCHAR,
	thinfilm_other VARCHAR,
	other_materials BOOLEAN,
	net_metering_agreement VARCHAR,
	net_metering_dc_capacity_mw VARCHAR,
	virtual_net_metering_agreement VARCHAR,
	virtual_net_metering_dc_capacity_mw VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE utility.utility(
	utility_id BIGINT,
	utility_name VARCHAR,
	street_address VARCHAR,
	city VARCHAR,
	state VARCHAR,
	zip BIGINT,
	owner_of_plants_reported_on_form BOOLEAN,
	operator_of_plants_reported_on_form BOOLEAN,
	asset_manager_of_plants_reported_on_form BOOLEAN,
	other_relationships_with_plants_reported_on_form BOOLEAN,
	entity_type VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE wind.operable(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology BOOLEAN,
	prime_mover BOOLEAN,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw NUMERIC(18, 6),
	winter_capacity_mw NUMERIC(18, 6),
	operating_month BIGINT,
	operating_year BIGINT,
	number_of_turbines BIGINT,
	predominant_turbine_manufacturer VARCHAR,
	predominant_turbine_model_number VARCHAR,
	design_wind_speed_mph NUMERIC(18, 6),
	wind_quality_class BIGINT,
	turbine_hub_height_feet NUMERIC(18, 6),
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE wind.retired_and_canceled(
	utility_id BIGINT,
	utility_name VARCHAR,
	plant_code BIGINT,
	plant_name VARCHAR,
	state VARCHAR,
	county VARCHAR,
	generator_id VARCHAR,
	status VARCHAR,
	technology VARCHAR,
	prime_mover VARCHAR,
	sector_name VARCHAR,
	sector BIGINT,
	nameplate_capacity_mw NUMERIC(18, 6),
	summer_capacity_mw VARCHAR,
	winter_capacity_mw VARCHAR,
	operating_month VARCHAR,
	operating_year VARCHAR,
	retirement_month VARCHAR,
	retirement_year VARCHAR,
	number_of_turbines VARCHAR,
	predominant_turbine_manufacturer VARCHAR,
	predominant_turbine_model_number VARCHAR,
	design_wind_speed_mph VARCHAR,
	wind_quality_class VARCHAR,
	turbine_hub_height_feet VARCHAR,
	file_year INT NOT NULL,
	file_date TIMESTAMP NOT NULL,
	upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
